# Generated by Django 3.2.5 on 2021-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_portal', '0002_securitykeymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitykeymodel',
            name='securitykey',
            field=models.BigIntegerField(),
        ),
    ]
