# Generated by Django 3.2.5 on 2021-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_portal', '0003_alter_securitykeymodel_securitykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hostel', models.TextField()),
                ('block', models.CharField(max_length=2)),
                ('floor', models.SmallIntegerField()),
                ('roomno', models.SmallIntegerField()),
                ('cmplnttype', models.TextField()),
                ('complaint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
