# Generated by Django 3.2.5 on 2021-07-14 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_portal', '0004_usercomplaint_usercomplaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signupmodel',
        ),
        migrations.DeleteModel(
            name='UserComplaints',
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
