# Generated by Django 3.2.5 on 2021-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_portal', '0006_alter_usercomplaint_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('hostel', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=5)),
                ('floor', models.SmallIntegerField()),
                ('hygieneissue', models.CharField(max_length=20)),
                ('hygieneissueTXT', models.TextField(default='')),
                ('qualityissue', models.CharField(max_length=20)),
                ('qualityissueTXT', models.TextField(default='')),
                ('messrating', models.SmallIntegerField()),
                ('suggestions', models.TextField(default='')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='usercomplaint',
            options={'ordering': ['-datetime']},
        ),
    ]
