# Generated by Django 3.2.5 on 2021-07-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_portal', '0007_auto_20210716_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
